pub fn normalize_event_tag(event_type: usize, sub_event: u32) -> String {
    match event_type {
        0 => "create".to_string(),
        1 => "destroy".to_string(),
        2 => format!("alarm:{sub_event}"),
        3 => match sub_event {
            0 => "step".to_string(),
            1 => "step:begin".to_string(),
            2 => "step:end".to_string(),
            _ => format!("step:{sub_event}"),
        },
        4 => "collision".to_string(),
        5 => format!("keyboard:{}", format_key_name(sub_event)),
        6 => match sub_event {
            0 => "mouse:left".to_string(),
            1 => "mouse:right".to_string(),
            2 => "mouse:middle".to_string(),
            3 => "mouse:no-button".to_string(),
            4 => "mouse:left-pressed".to_string(),
            5 => "mouse:right-pressed".to_string(),
            6 => "mouse:middle-pressed".to_string(),
            7 => "mouse:left-released".to_string(),
            8 => "mouse:right-released".to_string(),
            9 => "mouse:middle-released".to_string(),
            10 => "mouse:enter".to_string(),
            11 => "mouse:leave".to_string(),
            12 => "mouse:global-pressed".to_string(),
            13 => "mouse:global-released".to_string(),
            50 => "mouse:global-left".to_string(),
            51 => "mouse:global-right".to_string(),
            52 => "mouse:global-middle".to_string(),
            53 => "mouse:global-left-pressed".to_string(),
            54 => "mouse:global-right-pressed".to_string(),
            55 => "mouse:global-middle-pressed".to_string(),
            56 => "mouse:global-left-released".to_string(),
            57 => "mouse:global-right-released".to_string(),
            58 => "mouse:global-middle-released".to_string(),
            60 => "mouse:wheel-up".to_string(),
            61 => "mouse:wheel-down".to_string(),
            _ => format!("mouse:{sub_event}"),
        },
        7 => match sub_event {
            0 => "other:outside".to_string(),
            1 => "other:boundary".to_string(),
            2 => "other:game-start".to_string(),
            3 => "other:game-end".to_string(),
            4 => "other:room-start".to_string(),
            5 => "other:room-end".to_string(),
            6 => "other:no-health".to_string(),
            7 => "other:animation-end".to_string(),
            8 => "other:end-of-path".to_string(),
            9 => "other:no-more-lives".to_string(),
            10 => "other:animation-update".to_string(),
            11 => "other:user0".to_string(),
            12 => "other:user1".to_string(),
            13 => "other:user2".to_string(),
            14 => "other:user3".to_string(),
            15 => "other:user4".to_string(),
            16 => "other:user5".to_string(),
            17 => "other:user6".to_string(),
            18 => "other:user7".to_string(),
            19 => "other:user8".to_string(),
            20 => "other:user9".to_string(),
            21 => "other:user10".to_string(),
            22 => "other:user11".to_string(),
            23 => "other:user12".to_string(),
            24 => "other:user13".to_string(),
            25 => "other:user14".to_string(),
            26 => "other:user15".to_string(),
            n if (40..48).contains(&n) => format!("other:outside-view-{}", n - 40),
            n if (50..58).contains(&n) => format!("other:intersect-view-{}", n - 50),
            _ => format!("other:{sub_event}"),
        },
        8 => "draw".to_string(),
        9 => format!("keypress:{}", format_key_name(sub_event)),
        10 => format!("keyrelease:{}", format_key_name(sub_event)),
        11 => format!("trigger:{sub_event}"),
        _ => format!("event:{event_type}-{sub_event}"),
    }
}

pub fn format_key_name(sub_event: u32) -> String {
    let key = sub_event as u8 as char;
    if key.is_ascii_alphanumeric() {
        key.to_ascii_lowercase().to_string()
    } else {
        format!("0x{:02x}", sub_event as u8)
    }
}
